name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: iwamot/workflows/.github/workflows/ci.yml@c84493dcba63d8adaebd887d406f40dfec2af5a1 # v0.9.0
