name: 'Dependency review'
on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    uses: iwamot/workflows/.github/workflows/dependency-review.yml@fb6b31c58b26c1baaa822c1a2798d00e5fddef27 # v0.7.0
