name: Publish Docker images

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  publish:
    uses: iwamot/workflows/.github/workflows/publish-ecr-public.yml@87fc7cf164c94bcd8515158b76dac3c30fda5ac9 # v0.10.2
    permissions:
      contents: read
      id-token: write
    with:
      registry_image: public.ecr.aws/k7d3h0b5/iwamot/marp-agent-mcp
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
