name: Publish Docker images

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  publish:
    uses: iwamot/workflows/.github/workflows/publish-ecr-public.yml@b3d2f10167c0cb280d7307b4cbc3dfff42e11c7b # v0.10.5
    permissions:
      contents: read
      id-token: write
    with:
      registry_image: public.ecr.aws/k7d3h0b5/iwamot/marp-agent-mcp
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
