name: Publish Docker images

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  publish:
    uses: iwamot/workflows/.github/workflows/publish-ecr-public.yml@b292dc0f0ff30f059a866ea6e72acbc9245952ab # v0.10.1
    permissions:
      contents: read
      id-token: write
    with:
      registry_image: public.ecr.aws/k7d3h0b5/iwamot/marp-agent-mcp
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
